use pulldown_cmark::{html, Options, Parser};
use serde::{Deserialize, Serialize};
use std::sync::OnceLock;
use syntect::easy::HighlightLines;
use syntect::highlighting::{Color, Theme, ThemeSet};
use syntect::html::{styled_line_to_highlighted_html, IncludeBackground};
use syntect::parsing::SyntaxSet;
use syntect::util::LinesWithEndings;

// ---- Embedded KaTeX assets (generated by scripts/bundle-katex.mjs) ----
const KATEX_CSS: &str = include_str!("../katex/katex-embedded.css");
const KATEX_JS: &str = include_str!("../katex/katex.min.js");
const KATEX_AUTORENDER_JS: &str = include_str!("../katex/auto-render.min.js");

// Injected before </body>: render every math span found in the document.
fn katex_body_script() -> String {
    format!(
        "<script>{}</script>\n<script>{}</script>\n<script>\n\
         document.addEventListener('DOMContentLoaded', function() {{\n\
           renderMathInElement(document.body, {{\n\
             delimiters: [\n\
               {{left: '$$', right: '$$', display: true}},\n\
               {{left: '\\\\[', right: '\\\\]', display: true}},\n\
               {{left: '\\\\(', right: '\\\\)', display: false}},\n\
               {{left: '$', right: '$', display: false}}\n\
             ],\n\
             throwOnError: false,\n\
             ignoredClasses: ['highlight', 'input_area', 'output_text']\n\
           }});\n\
           window.__katexDone = true;\n\
         }});\n\
         </script>",
        KATEX_JS, KATEX_AUTORENDER_JS
    )
}

// ---- syntect caches (parsed once, reused for every cell) ----
fn syntax_set() -> &'static SyntaxSet {
    static SS: OnceLock<SyntaxSet> = OnceLock::new();
    SS.get_or_init(SyntaxSet::load_defaults_newlines)
}

fn theme_set() -> &'static ThemeSet {
    static TS: OnceLock<ThemeSet> = OnceLock::new();
    TS.get_or_init(ThemeSet::load_defaults)
}

fn syntect_theme_name(code_theme: &str, doc_theme: &str) -> &'static str {
    match code_theme {
        "monokai" => "base16-eighties.dark",
        "github" => "InspiredGitHub",
        "vscode-dark" => "base16-ocean.dark",
        _ => {
            if doc_theme == "dark" {
                "base16-ocean.dark"
            } else {
                "InspiredGitHub"
            }
        }
    }
}

fn resolve_theme(code_theme: &str, doc_theme: &str) -> &'static Theme {
    let ts = theme_set();
    let name = syntect_theme_name(code_theme, doc_theme);
    ts.themes
        .get(name)
        .or_else(|| ts.themes.get("InspiredGitHub"))
        .unwrap_or_else(|| ts.themes.values().next().expect("at least one theme"))
}

fn color_css(c: Color) -> String {
    format!("#{:02x}{:02x}{:02x}", c.r, c.g, c.b)
}

// Map a notebook language to a syntect token. Defaults to python.
fn notebook_language(notebook: &Notebook) -> String {
    notebook
        .metadata
        .as_ref()
        .and_then(|m| m.get("language_info"))
        .and_then(|l| l.get("name"))
        .and_then(|n| n.as_str())
        .or_else(|| {
            notebook
                .metadata
                .as_ref()
                .and_then(|m| m.get("kernelspec"))
                .and_then(|k| k.get("language"))
                .and_then(|n| n.as_str())
        })
        .unwrap_or("python")
        .to_string()
}

fn syntax_highlight(code: &str, lang: &str, theme: &Theme) -> String {
    let ss = syntax_set();
    let syntax = ss
        .find_syntax_by_token(lang)
        .or_else(|| ss.find_syntax_by_extension(lang))
        .unwrap_or_else(|| ss.find_syntax_plain_text());
    let mut highlighter = HighlightLines::new(syntax, theme);
    let mut out = String::new();
    for line in LinesWithEndings::from(code) {
        match highlighter.highlight_line(line, ss) {
            Ok(ranges) => {
                let line_html = styled_line_to_highlighted_html(&ranges[..], IncludeBackground::No)
                    .unwrap_or_else(|_| html_escape(line));
                out.push_str(&line_html);
            }
            Err(_) => out.push_str(&html_escape(line)),
        }
    }
    out
}

// Render a markdown cell, protecting LaTeX math from the markdown parser so
// constructs like `$x_i$` aren't mangled into `<em>` before KaTeX sees them.
fn render_markdown(source: &str) -> String {
    let (protected, math) = protect_math(source);

    let mut opts = Options::empty();
    opts.insert(Options::ENABLE_TABLES);
    opts.insert(Options::ENABLE_STRIKETHROUGH);
    opts.insert(Options::ENABLE_TASKLISTS);
    opts.insert(Options::ENABLE_FOOTNOTES);
    opts.insert(Options::ENABLE_SMART_PUNCTUATION);

    let parser = Parser::new_ext(&protected, opts);
    let mut md_html = String::new();
    html::push_html(&mut md_html, parser);

    // Restore math spans (HTML-escaped so KaTeX reads the raw LaTeX source).
    for (i, raw) in math.iter().enumerate() {
        let token = math_placeholder(i);
        md_html = md_html.replace(&token, &html_escape(raw));
    }
    md_html
}

fn math_placeholder(i: usize) -> String {
    format!("xMATHxPLACEHOLDERx{}x", i)
}

// Extract `$...$`, `$$...$$`, `\(...\)`, `\[...\]` regions and replace them with
// inert alphanumeric placeholders. Skips inline code spans and fenced blocks so
// a literal `$` inside code isn't treated as math.
fn protect_math(src: &str) -> (String, Vec<String>) {
    let chars: Vec<char> = src.chars().collect();
    let mut out = String::new();
    let mut math: Vec<String> = Vec::new();
    let mut i = 0;
    let n = chars.len();

    let push_math = |out: &mut String, math: &mut Vec<String>, raw: String| {
        out.push_str(&math_placeholder(math.len()));
        math.push(raw);
    };

    while i < n {
        let c = chars[i];

        // Fenced code block ``` or ~~~ : copy verbatim until the closing fence.
        if (c == '`' || c == '~') && at_line_start(&chars, i) {
            let fence = c;
            let mut run = 0;
            while i + run < n && chars[i + run] == fence {
                run += 1;
            }
            if run >= 3 {
                let start = i;
                i += run;
                // consume to end of line, then to closing fence line
                loop {
                    while i < n && chars[i] != '\n' {
                        i += 1;
                    }
                    if i >= n {
                        break;
                    }
                    i += 1; // past newline
                    let mut close = 0;
                    while i + close < n && chars[i + close] == fence {
                        close += 1;
                    }
                    if close >= run {
                        i += close;
                        break;
                    }
                }
                out.extend(chars[start..i.min(n)].iter());
                continue;
            }
        }

        // Inline code span: copy verbatim until matching backtick run.
        if c == '`' {
            let mut run = 0;
            while i + run < n && chars[i + run] == '`' {
                run += 1;
            }
            let start = i;
            i += run;
            while i < n {
                if chars[i] == '`' {
                    let mut close = 0;
                    while i + close < n && chars[i + close] == '`' {
                        close += 1;
                    }
                    if close == run {
                        i += close;
                        break;
                    }
                    i += close;
                } else {
                    i += 1;
                }
            }
            out.extend(chars[start..i.min(n)].iter());
            continue;
        }

        // Display math $$ ... $$
        if c == '$' && i + 1 < n && chars[i + 1] == '$' {
            if let Some(end) = find_seq(&chars, i + 2, &['$', '$']) {
                let raw: String = chars[i..end + 2].iter().collect();
                push_math(&mut out, &mut math, raw);
                i = end + 2;
                continue;
            }
        }

        // Inline math $ ... $  (not a lone $, not crossing a blank line)
        if c == '$' && i + 1 < n && chars[i + 1] != '$' && !chars[i + 1].is_whitespace() {
            if let Some(end) = find_inline_dollar(&chars, i + 1) {
                let raw: String = chars[i..end + 1].iter().collect();
                push_math(&mut out, &mut math, raw);
                i = end + 1;
                continue;
            }
        }

        // \[ ... \] and \( ... \)
        if c == '\\' && i + 1 < n && (chars[i + 1] == '[' || chars[i + 1] == '(') {
            let (close_a, close_b) = if chars[i + 1] == '[' {
                ('\\', ']')
            } else {
                ('\\', ')')
            };
            if let Some(end) = find_seq(&chars, i + 2, &[close_a, close_b]) {
                let raw: String = chars[i..end + 2].iter().collect();
                push_math(&mut out, &mut math, raw);
                i = end + 2;
                continue;
            }
        }

        out.push(c);
        i += 1;
    }

    (out, math)
}

fn at_line_start(chars: &[char], i: usize) -> bool {
    i == 0 || chars[i - 1] == '\n'
}

// Find the start index of the sequence `seq` at or after `from`.
fn find_seq(chars: &[char], from: usize, seq: &[char]) -> Option<usize> {
    let n = chars.len();
    let mut i = from;
    while i + seq.len() <= n {
        if chars[i..i + seq.len()] == *seq {
            return Some(i);
        }
        i += 1;
    }
    None
}

// Find the closing `$` of an inline math span, staying on the logical line.
fn find_inline_dollar(chars: &[char], from: usize) -> Option<usize> {
    let n = chars.len();
    let mut i = from;
    while i < n {
        match chars[i] {
            '\\' => i += 2, // skip escaped char
            '\n' if i + 1 < n && chars[i + 1] == '\n' => return None, // blank line ends it
            '$' => return Some(i),
            _ => i += 1,
        }
    }
    None
}

#[derive(Debug, Deserialize, Serialize)]
pub struct Notebook {
    pub cells: Vec<Cell>,
    pub metadata: Option<serde_json::Value>,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct Cell {
    pub cell_type: String,
    pub source: Source,
    pub outputs: Option<Vec<Output>>,
    pub execution_count: Option<serde_json::Value>,
    pub metadata: Option<serde_json::Value>,
}

#[derive(Debug, Deserialize, Serialize)]
#[serde(untagged)]
pub enum Source {
    String(String),
    Array(Vec<String>),
}

impl Source {
    pub fn to_string(&self) -> String {
        match self {
            Source::String(s) => s.clone(),
            Source::Array(arr) => arr.join(""),
        }
    }
}

#[derive(Debug, Deserialize, Serialize)]
pub struct Output {
    pub output_type: String,
    pub text: Option<Source>,
    pub data: Option<OutputData>,
    pub ename: Option<String>,
    pub evalue: Option<String>,
    pub traceback: Option<Vec<String>>,
    pub execution_count: Option<serde_json::Value>,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct OutputData {
    #[serde(rename = "text/plain")]
    pub text_plain: Option<Source>,
    #[serde(rename = "text/html")]
    pub text_html: Option<Source>,
    #[serde(rename = "image/svg+xml")]
    pub image_svg: Option<Source>,
    #[serde(rename = "image/png")]
    pub image_png: Option<String>,
    #[serde(rename = "image/jpeg")]
    pub image_jpeg: Option<String>,
}

pub fn notebook_to_html_with_options(
    notebook_json: &str,
    theme: Option<&str>,
    code_theme: Option<&str>,
    author: Option<&str>,
    show_date: bool,
    landscape: bool,
    serif: bool,
) -> Result<String, String> {
    let notebook: Notebook =
        serde_json::from_str(notebook_json).map_err(|e| format!("Failed to parse notebook: {}", e))?;

    let doc_theme = theme.unwrap_or("light");
    let code_theme = code_theme.unwrap_or("default");
    let language = notebook_language(&notebook);
    let syntect_theme = resolve_theme(code_theme, doc_theme);
    let code_bg = syntect_theme
        .settings
        .background
        .map(color_css)
        .unwrap_or_else(|| "#f7f7f7".to_string());
    let code_fg = syntect_theme
        .settings
        .foreground
        .map(color_css)
        .unwrap_or_else(|| "#1a1a1a".to_string());

    let mut html_content = String::new();

    // Generate themed HTML head with orientation, KaTeX styles and typography.
    let theme_css = get_theme_css_with_orientation(doc_theme, landscape, serif);
    html_content.push_str(&theme_css);

    // Add header with author and date if specified
    if (author.is_some() && !author.unwrap_or("").is_empty()) || show_date {
        html_content.push_str("<div class=\"pdf-header\">");
        // Author on left (or empty span for spacing)
        if let Some(author_name) = author {
            if !author_name.is_empty() {
                html_content.push_str(&format!("<span class=\"author\">Author: {}</span>", html_escape(author_name)));
            } else {
                html_content.push_str("<span class=\"author\"></span>");
            }
        } else {
            html_content.push_str("<span class=\"author\"></span>");
        }
        // Date on right (or empty span for spacing)
        if show_date {
            let date = chrono::Local::now().format("%B %d, %Y").to_string();
            html_content.push_str(&format!("<span class=\"date\">{}</span>", date));
        } else {
            html_content.push_str("<span class=\"date\"></span>");
        }
        html_content.push_str("</div>");
    }

    for (i, cell) in notebook.cells.iter().enumerate() {
        match cell.cell_type.as_str() {
            "markdown" => {
                let source = cell.source.to_string();
                let md_html = render_markdown(&source);
                html_content.push_str(&format!(
                    "<div class=\"cell text_cell\" id=\"cell-{}\">\n<div class=\"inner_cell\">\n<div class=\"text_cell_render rendered_html\">\n{}\n</div>\n</div>\n</div>\n",
                    i, md_html
                ));
            }
            "code" => {
                let source = cell.source.to_string();
                let highlighted = syntax_highlight(&source, &language, syntect_theme);
                let exec_count = cell.execution_count
                    .as_ref()
                    .and_then(|v| v.as_i64())
                    .map(|n| n.to_string())
                    .unwrap_or_else(|| " ".to_string());

                html_content.push_str(&format!(
                    "<div class=\"cell code_cell\" id=\"cell-{}\">\n<div class=\"input\">\n<div class=\"prompt input_prompt\">In[{}]:</div>\n<div class=\"inner_cell\">\n<div class=\"input_area\" style=\"background:{};color:{}\">\n<div class=\"highlight\"><pre style=\"background:{};color:{}\">{}</pre></div>\n</div>\n</div>\n</div>\n",
                    i, exec_count, code_bg, code_fg, code_bg, code_fg, highlighted
                ));

                if let Some(outputs) = &cell.outputs {
                    for output in outputs {
                        let out_count = output.execution_count
                            .as_ref()
                            .and_then(|v| v.as_i64())
                            .map(|n| n.to_string())
                            .unwrap_or_else(|| exec_count.clone());
                        html_content.push_str(&render_output(output, &out_count));
                    }
                }

                html_content.push_str("</div>\n");
            }
            "raw" => {
                let source = cell.source.to_string();
                html_content.push_str(&format!(
                    "<div class=\"cell raw_cell\" id=\"cell-{}\">\n<pre>{}</pre>\n</div>\n",
                    i, html_escape(&source)
                ));
            }
            _ => {}
        }
    }

    // Render any LaTeX math just before the document closes.
    html_content.push_str(&katex_body_script());
    html_content.push_str("</div>\n</body>\n</html>");

    Ok(html_content)
}

fn get_theme_css_with_orientation(theme: &str, landscape: bool, serif: bool) -> String {
    let base_css = match theme {
        "dark" => DARK_THEME_CSS,
        "solarized" => SOLARIZED_THEME_CSS,
        _ => JUPYTER_HTML_HEAD,
    };

    let mut result = base_css.to_string();

    // Replace @page orientation if landscape
    if landscape {
        result = result.replace("size: A4;", "size: A4 landscape;");
    }

    // Typography + KaTeX styles, injected last so they win the cascade.
    let body_font = if serif {
        "'Latin Modern Roman', Georgia, Cambria, 'Times New Roman', serif"
    } else {
        "'Outfit', -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif"
    };
    let typography = format!(
        "body {{ font-family: {}; }}\n\
         .rendered_html p, .rendered_html li {{ hyphens: auto; -webkit-hyphens: auto; }}\n\
         .katex-display {{ overflow-x: auto; overflow-y: hidden; }}\n\
         .output_svg {{ text-align: center; page-break-inside: avoid; }}\n\
         .output_svg svg {{ max-width: 100%; height: auto; }}\n",
        body_font
    );

    let injection = format!("{}\n{}</style>", typography, katex_head_inline());
    result = result.replace("</style>", &injection);

    result
}

// KaTeX CSS without the <style> wrapper (injected inside the page's <style>).
fn katex_head_inline() -> String {
    KATEX_CSS.to_string()
}

fn render_output(output: &Output, exec_count: &str) -> String {
    let mut html = String::new();

    match output.output_type.as_str() {
        "stream" => {
            if let Some(text) = &output.text {
                html.push_str("<div class=\"output_wrapper\">\n");
                html.push_str("<div class=\"output\">\n");
                html.push_str("<div class=\"output_area\">\n");
                html.push_str("<div class=\"prompt\"></div>\n");
                html.push_str("<div class=\"output_subarea output_stream output_stdout output_text\">\n");
                html.push_str(&format!("<pre>{}</pre>\n", html_escape(&text.to_string())));
                html.push_str("</div>\n</div>\n</div>\n</div>\n");
            }
        }
        "execute_result" | "display_data" => {
            if let Some(data) = &output.data {
                html.push_str("<div class=\"output_wrapper\">\n");
                html.push_str("<div class=\"output\">\n");
                html.push_str("<div class=\"output_area\">\n");
                
                if output.output_type == "execute_result" {
                    html.push_str(&format!("<div class=\"prompt output_prompt\">Out[{}]:</div>\n", exec_count));
                } else {
                    html.push_str("<div class=\"prompt\"></div>\n");
                }

                if let Some(svg) = &data.image_svg {
                    // Inline vector SVG renders crisp at any zoom (unlike a raster PNG).
                    html.push_str("<div class=\"output_subarea output_svg\">\n");
                    html.push_str(&svg.to_string());
                    html.push_str("\n</div>\n");
                } else if let Some(img) = &data.image_png {
                    let clean_img = img.replace("\n", "").replace(" ", "");
                    html.push_str("<div class=\"output_subarea output_png\">\n");
                    html.push_str(&format!("<img src=\"data:image/png;base64,{}\" />\n", clean_img));
                    html.push_str("</div>\n");
                } else if let Some(img) = &data.image_jpeg {
                    let clean_img = img.replace("\n", "").replace(" ", "");
                    html.push_str("<div class=\"output_subarea output_jpeg\">\n");
                    html.push_str(&format!("<img src=\"data:image/jpeg;base64,{}\" />\n", clean_img));
                    html.push_str("</div>\n");
                } else if let Some(text_html) = &data.text_html {
                    html.push_str("<div class=\"output_subarea output_html rendered_html\">\n");
                    html.push_str(&text_html.to_string());
                    html.push_str("\n</div>\n");
                } else if let Some(text) = &data.text_plain {
                    html.push_str("<div class=\"output_subarea output_text output_result\">\n");
                    html.push_str(&format!("<pre>{}</pre>\n", html_escape(&text.to_string())));
                    html.push_str("</div>\n");
                }

                html.push_str("</div>\n</div>\n</div>\n");
            }
        }
        "error" => {
            let mut error_text = String::new();
            if let Some(traceback) = &output.traceback {
                error_text.push_str(&traceback.join("\n"));
            } else {
                if let Some(ename) = &output.ename {
                    error_text.push_str(ename);
                }
                if let Some(evalue) = &output.evalue {
                    error_text.push_str(&format!(": {}", evalue));
                }
            }
            let clean_error = strip_ansi_codes(&error_text);
            html.push_str("<div class=\"output_wrapper\">\n");
            html.push_str("<div class=\"output\">\n");
            html.push_str("<div class=\"output_area\">\n");
            html.push_str("<div class=\"prompt\"></div>\n");
            html.push_str("<div class=\"output_subarea output_error\">\n");
            html.push_str(&format!("<pre>{}</pre>\n", html_escape(&clean_error)));
            html.push_str("</div>\n</div>\n</div>\n</div>\n");
        }
        _ => {}
    }

    html
}

fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}

fn strip_ansi_codes(s: &str) -> String {
    let re = regex::Regex::new(r"\x1b\[[0-9;]*m").unwrap_or_else(|_| regex::Regex::new("").unwrap());
    re.replace_all(s, "").to_string()
}

const JUPYTER_HTML_HEAD: &str = r#"<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        @page {
            size: A4;
            margin: 2cm 2.5cm;
        }

        * {
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
            font-size: 11pt;
            line-height: 1.6;
            color: #333;
            background-color: #fff;
            margin: 0;
            padding: 20px;
        }

        .pdf-header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 6px 0;
            margin-bottom: 12px;
            border-bottom: 1px solid #ddd;
            color: #666;
            font-size: 9pt;
            page-break-after: avoid;
            break-after: avoid;
        }

        .pdf-header .author {
            text-align: left;
        }

        .pdf-header .date {
            text-align: right;
        }
        
        #notebook-container {
            max-width: 100%;
            margin: 0;
            padding: 0;
        }

        .cell {
            margin-bottom: 16px;
            position: relative;
            page-break-inside: avoid;
        }

        /* Keep code cell and its output together */
        .code_cell {
            page-break-inside: avoid;
        }

        /* Markdown cells */
        .text_cell {
            page-break-inside: avoid;
        }

        .text_cell .rendered_html {
            padding: 8px 0;
        }

        .rendered_html h1 {
            font-size: 1.8em;
            font-weight: bold;
            margin: 0.8em 0 0.4em 0;
            border-bottom: 1px solid #ddd;
            padding-bottom: 0.3em;
            page-break-after: avoid;
        }

        .rendered_html h2 {
            font-size: 1.4em;
            font-weight: bold;
            margin: 0.8em 0 0.4em 0;
            border-bottom: 1px solid #eee;
            padding-bottom: 0.2em;
            page-break-after: avoid;
        }

        .rendered_html h3 {
            font-size: 1.2em;
            font-weight: bold;
            margin: 0.8em 0 0.4em 0;
            page-break-after: avoid;
        }

        .rendered_html h4 {
            font-size: 1.1em;
            font-weight: bold;
            margin: 0.8em 0 0.4em 0;
            page-break-after: avoid;
        }

        .rendered_html p {
            margin: 0.8em 0;
            text-align: justify;
            orphans: 3;
            widows: 3;
        }

        .rendered_html ul, .rendered_html ol {
            margin: 0.8em 0;
            padding-left: 2em;
        }

        .rendered_html li {
            margin: 0.3em 0;
        }

        .rendered_html strong {
            font-weight: bold;
        }

        .rendered_html em {
            font-style: italic;
        }

        .rendered_html code {
            background-color: #f4f4f4;
            padding: 2px 5px;
            border-radius: 3px;
            font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace;
            font-size: 0.9em;
        }

        .rendered_html pre {
            background-color: #f4f4f4;
            padding: 10px;
            border-radius: 4px;
            overflow-x: auto;
            font-size: 0.9em;
        }

        .rendered_html table {
            border-collapse: collapse;
            margin: 0.8em auto;
            width: auto;
        }

        .rendered_html th, .rendered_html td {
            border: 1px solid #ddd;
            padding: 6px 10px;
            text-align: left;
        }

        .rendered_html th {
            background-color: #f4f4f4;
            font-weight: bold;
        }

        /* Code cells - centered and smaller */
        .code_cell {
            margin: 12px auto;
            max-width: 95%;
        }

        .code_cell .input {
            display: flex;
            align-items: flex-start;
        }

        .prompt {
            font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace;
            font-size: 10pt;
            min-width: 60px;
            color: #303F9F;
            text-align: right;
            padding-right: 10px;
            padding-top: 6px;
            flex-shrink: 0;
        }

        .input_prompt {
            color: #303F9F;
            font-weight: bold;
        }

        .output_prompt {
            color: #D84315;
            font-weight: bold;
        }

        .inner_cell {
            flex: 1;
            min-width: 0;
        }

        .input_area {
            background-color: #f7f7f7;
            border: 1px solid #cfcfcf;
            border-radius: 2px;
            padding: 6px 10px;
        }

        .input_area pre {
            margin: 0;
            font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace;
            font-size: 10pt;
            line-height: 1.4;
            white-space: pre-wrap;
            word-wrap: break-word;
        }

        /* Syntax highlighting - Jupyter style */
        .k { color: #008000; font-weight: bold; }  /* Keywords */
        .kn { color: #008000; font-weight: bold; } /* Keyword namespace (import, from) */
        .nb { color: #008000; }                     /* Builtins */
        .nf { color: #0000FF; }                     /* Function names */
        .s, .s1, .s2 { color: #BA2121; }           /* Strings */
        .c1 { color: #408080; font-style: italic; } /* Comments */
        .mi, .mf { color: #666666; }               /* Numbers */
        .o { color: #666666; }                      /* Operators */
        .nn { color: #0000FF; font-weight: bold; } /* Module names */
        .bp { color: #008000; }                     /* Built-in pseudo */

        /* Output area */
        .output_wrapper {
            margin-top: 6px;
            page-break-before: avoid;
        }

        .output {
            display: flex;
            flex-direction: column;
        }

        .output_area {
            display: flex;
            align-items: flex-start;
        }

        .output_subarea {
            flex: 1;
            padding: 6px 0;
            overflow-x: auto;
        }

        .output_text pre {
            margin: 0;
            font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace;
            font-size: 10pt;
            line-height: 1.4;
            white-space: pre-wrap;
            word-wrap: break-word;
        }

        .output_png, .output_jpeg {
            text-align: center;
            page-break-inside: avoid;
        }

        .output_png img, .output_jpeg img {
            max-width: 90%;
            height: auto;
            display: block;
            margin: 8px auto;
        }

        .output_html {
            overflow-x: auto;
        }

        .output_html table {
            border-collapse: collapse;
            margin: 0 auto;
        }

        .output_html th, .output_html td {
            border: 1px solid #ddd;
            padding: 5px 8px;
            text-align: left;
            font-size: 10pt;
        }

        .output_html th {
            background-color: #f4f4f4;
        }

        .output_error {
            background-color: #ffdddd;
            border-radius: 4px;
            padding: 6px 10px;
        }

        .output_error pre {
            margin: 0;
            color: #cc0000;
            font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace;
            font-size: 10pt;
        }

        /* Print styles */
        @media print {
            body {
                background: white;
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
            }
            #notebook-container {
                max-width: none;
                padding: 0;
            }
            .cell {
                page-break-inside: avoid;
            }
            .code_cell {
                page-break-inside: avoid;
            }
            .output_wrapper {
                page-break-before: avoid;
            }
            .rendered_html h1, .rendered_html h2, .rendered_html h3, .rendered_html h4 {
                page-break-after: avoid;
            }
        }
    </style>
</head>
<body>
<div id="notebook-container">
"#;

const DARK_THEME_CSS: &str = r#"<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        @page {
            size: A4;
            margin: 2cm 2.5cm;
        }

        * { box-sizing: border-box; }

        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
            font-size: 11pt;
            line-height: 1.6;
            color: #e0e0e0;
            background-color: #1e1e1e;
            margin: 0;
            padding: 0;
        }

        .pdf-header {
            display: flex;
            justify-content: space-between;
            padding: 6px 0;
            margin-bottom: 12px;
            border-bottom: 1px solid #444;
            color: #888;
            font-size: 9pt;
            page-break-after: avoid;
            break-after: avoid;
        }

        #notebook-container { max-width: 100%; margin: 0; padding: 0; }
        .cell { margin-bottom: 16px; position: relative; page-break-inside: avoid; }
        .code_cell { page-break-inside: avoid; }
        .text_cell { page-break-inside: avoid; }
        .text_cell .rendered_html { padding: 8px 0; }
        .rendered_html h1 { font-size: 1.8em; font-weight: bold; margin: 0.8em 0 0.4em 0; border-bottom: 1px solid #444; padding-bottom: 0.3em; color: #fff; }
        .rendered_html h2 { font-size: 1.4em; font-weight: bold; margin: 0.8em 0 0.4em 0; border-bottom: 1px solid #333; padding-bottom: 0.2em; color: #fff; }
        .rendered_html h3 { font-size: 1.2em; font-weight: bold; margin: 0.6em 0 0.3em 0; color: #fff; }
        .rendered_html p { margin: 0.5em 0; }
        .rendered_html ul, .rendered_html ol { margin: 0.5em 0; padding-left: 2em; }
        .rendered_html li { margin: 0.2em 0; }
        .rendered_html code { background-color: #333; padding: 2px 6px; border-radius: 3px; font-family: "SFMono-Regular", Consolas, monospace; font-size: 0.9em; color: #f8f8f2; }
        .rendered_html pre { background-color: #2d2d2d; padding: 12px; border-radius: 4px; overflow-x: auto; }
        .rendered_html pre code { background: none; padding: 0; }
        .rendered_html blockquote { border-left: 4px solid #666; margin: 0.5em 0; padding-left: 1em; color: #aaa; }
        .rendered_html table { border-collapse: collapse; margin: 0.5em 0; }
        .rendered_html th, .rendered_html td { border: 1px solid #444; padding: 6px 12px; }
        .rendered_html th { background-color: #333; }
        .input { display: flex; margin-bottom: 4px; }
        .prompt { font-family: monospace; font-size: 10pt; color: #888; min-width: 80px; padding-right: 8px; text-align: right; flex-shrink: 0; }
        .input_prompt { color: #4a9eff; }
        .output_prompt { color: #ff6b6b; }
        .inner_cell { flex: 1; min-width: 0; }
        .input_area { background-color: #2d2d2d; border: 1px solid #444; border-radius: 4px; padding: 8px 12px; }
        .highlight pre { margin: 0; font-family: "SFMono-Regular", Consolas, monospace; font-size: 10pt; line-height: 1.4; white-space: pre-wrap; word-wrap: break-word; color: #f8f8f2; }
        .k { color: #ff79c6; font-weight: bold; }
        .kn { color: #ff79c6; font-weight: bold; }
        .nb { color: #8be9fd; }
        .nf { color: #50fa7b; }
        .s, .s1, .s2 { color: #f1fa8c; }
        .c1 { color: #6272a4; font-style: italic; }
        .mi, .mf { color: #bd93f9; }
        .o { color: #ff79c6; }
        .nn { color: #8be9fd; font-weight: bold; }
        .bp { color: #8be9fd; }
        .output_wrapper { margin-top: 6px; page-break-before: avoid; }
        .output { display: flex; flex-direction: column; }
        .output_area { display: flex; align-items: flex-start; }
        .output_subarea { flex: 1; min-width: 0; padding: 4px 0; }
        .output_text pre { font-family: "SFMono-Regular", Consolas, monospace; font-size: 10pt; margin: 0; white-space: pre-wrap; word-wrap: break-word; color: #e0e0e0; }
        .output_png img, .output_jpeg img { max-width: 100%; height: auto; }
        .output_error { background-color: #3d1f1f; border-radius: 4px; padding: 8px; }
        .output_error pre { color: #ff6b6b; font-family: monospace; font-size: 9pt; margin: 0; white-space: pre-wrap; }
        @media print {
            body { background-color: #1e1e1e !important; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
        }
    </style>
</head>
<body>
<div id="notebook-container">
"#;

const SOLARIZED_THEME_CSS: &str = r#"<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        @page {
            size: A4;
            margin: 2cm 2.5cm;
        }

        * { box-sizing: border-box; }

        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
            font-size: 11pt;
            line-height: 1.6;
            color: #657b83;
            background-color: #fdf6e3;
            margin: 0;
            padding: 0;
        }

        .pdf-header {
            display: flex;
            justify-content: space-between;
            padding: 6px 0;
            margin-bottom: 12px;
            border-bottom: 1px solid #eee8d5;
            color: #93a1a1;
            font-size: 9pt;
            page-break-after: avoid;
            break-after: avoid;
        }

        #notebook-container { max-width: 100%; margin: 0; padding: 0; }
        .cell { margin-bottom: 16px; position: relative; page-break-inside: avoid; }
        .code_cell { page-break-inside: avoid; }
        .text_cell { page-break-inside: avoid; }
        .text_cell .rendered_html { padding: 8px 0; }
        .rendered_html h1 { font-size: 1.8em; font-weight: bold; margin: 0.8em 0 0.4em 0; border-bottom: 1px solid #eee8d5; padding-bottom: 0.3em; color: #073642; }
        .rendered_html h2 { font-size: 1.4em; font-weight: bold; margin: 0.8em 0 0.4em 0; border-bottom: 1px solid #eee8d5; padding-bottom: 0.2em; color: #073642; }
        .rendered_html h3 { font-size: 1.2em; font-weight: bold; margin: 0.6em 0 0.3em 0; color: #073642; }
        .rendered_html p { margin: 0.5em 0; }
        .rendered_html code { background-color: #eee8d5; padding: 2px 6px; border-radius: 3px; font-family: "SFMono-Regular", Consolas, monospace; font-size: 0.9em; }
        .rendered_html pre { background-color: #eee8d5; padding: 12px; border-radius: 4px; overflow-x: auto; }
        .input { display: flex; margin-bottom: 4px; }
        .prompt { font-family: monospace; font-size: 10pt; color: #93a1a1; min-width: 80px; padding-right: 8px; text-align: right; flex-shrink: 0; }
        .input_prompt { color: #268bd2; }
        .output_prompt { color: #dc322f; }
        .inner_cell { flex: 1; min-width: 0; }
        .input_area { background-color: #eee8d5; border: 1px solid #93a1a1; border-radius: 4px; padding: 8px 12px; }
        .highlight pre { margin: 0; font-family: "SFMono-Regular", Consolas, monospace; font-size: 10pt; line-height: 1.4; white-space: pre-wrap; word-wrap: break-word; }
        .k { color: #859900; font-weight: bold; }
        .kn { color: #859900; font-weight: bold; }
        .nb { color: #b58900; }
        .nf { color: #268bd2; }
        .s, .s1, .s2 { color: #2aa198; }
        .c1 { color: #93a1a1; font-style: italic; }
        .mi, .mf { color: #d33682; }
        .o { color: #859900; }
        .nn { color: #268bd2; font-weight: bold; }
        .bp { color: #b58900; }
        .output_wrapper { margin-top: 6px; page-break-before: avoid; }
        .output { display: flex; flex-direction: column; }
        .output_area { display: flex; align-items: flex-start; }
        .output_subarea { flex: 1; min-width: 0; padding: 4px 0; }
        .output_text pre { font-family: "SFMono-Regular", Consolas, monospace; font-size: 10pt; margin: 0; white-space: pre-wrap; word-wrap: break-word; }
        @media print {
            body { background-color: #fdf6e3 !important; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
        }
    </style>
</head>
<body>
<div id="notebook-container">
"#;

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = r##"{
        "metadata": {"language_info": {"name": "python"}},
        "cells": [
            {"cell_type": "markdown", "source": "# Title\n\nInline $x_i$ and display:\n\n$$E = mc^2$$\n\n| a | b |\n|---|---|\n| 1 | 2 |\n"},
            {"cell_type": "code", "execution_count": 1, "source": "def f(x):\n    return x + 1\n", "outputs": [
                {"output_type": "execute_result", "execution_count": 1, "data": {"text/plain": "2"}}
            ]}
        ]
    }"##;

    fn html() -> String {
        notebook_to_html_with_options(SAMPLE, Some("light"), Some("default"), None, false, false, false)
            .expect("conversion should succeed")
    }

    #[test]
    fn math_is_protected_not_mangled() {
        let h = html();
        // The underscore in $x_i$ must NOT become <em>, and the math source survives.
        assert!(h.contains("$x_i$"), "inline math source preserved");
        assert!(!h.contains("x<em>i</em>"), "underscore not turned into emphasis");
        assert!(h.contains("$$E = mc^2$$"), "display math source preserved");
    }

    #[test]
    fn katex_assets_injected() {
        let h = html();
        assert!(h.contains(".katex"), "KaTeX CSS injected");
        assert!(h.contains("renderMathInElement"), "KaTeX render script injected");
    }

    #[test]
    fn gfm_table_renders() {
        let h = html();
        assert!(h.contains("<table>"), "GFM table converted to <table>");
    }

    #[test]
    fn code_is_syntax_highlighted() {
        let h = html();
        // syntect emits inline-styled spans
        assert!(h.contains("<span style=\"color:"), "syntect produced styled spans");
        assert!(h.contains("In[1]:"), "execution prompt rendered");
    }

    #[test]
    fn protect_math_skips_code_spans() {
        let (out, math) = protect_math("a `$not math$` b $real$ c");
        assert_eq!(math.len(), 1, "only the real math span is captured");
        assert!(out.contains("`$not math$`"), "code span left intact");
    }
}

